export { default as Login } from './login';
export { default as Register } from './register';
export { default as Home } from './home';
export { default as Cart } from './cart';
export { default as BuyerProduct } from './product/buyerProduct';
export { default as SellerProduct } from './product/sellerProduct';
export { default as Customer } from './customer';
export { default as ChangePass } from './changepass';
export { default as Deactive } from './deactive';
